<a href="https://colab.research.google.com/github/raghunathan-unisys/ML_Automation_Training/blob/Training-Notes/Day_1_ML_TrainingNotes_20231219.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# To install pacakages
- For installing using Python -> pip install pandas
- For installing using Anaconda -> conda install pandas

# To list all the installed packages
- ```pip freeze```
- ```help('modules')```

# To show the version of the package
- ```pip show package_name```
- ```print(package_name.__version__)```

In [14]:
# TO Print the Version of python being run

import platform
print(platform.python_version())

# OR

from platform import python_version
print(python_version())

3.10.12
3.10.12


# To Get the current working directory

In [16]:
# TO Get the current working directory

import os
print(os.getcwd())

# To change the working directory
# os.chdir('C:\Path')

/content


# Multiline statments

In [18]:
first_number = 10
second_number = 20

total = first_number +\
        second_number
print(total)

30


# Types of strings


In [21]:
word = "hello"
print(type(word))

my_string = "Hello There"
print(type(my_string))

my_paragraph = """This is a paragraph.
                  This is second line"""
print(type(my_paragraph))

# """
# If I am not storing this string in any variable, it will be considered
# as a mulltiline comment.
# """

<class 'str'>
<class 'str'>
<class 'str'>


# Removing deprication warnings in Google Colab

In [ ]:
# TO Ignore the warnings

import warnings
warnings.filterwarnings('ignore')

# TO Enable the warnings
import warnings
warnings.filterwarnings('default')

# Removing the warnings in Pandas


In [ ]:
# TO Remove the Pandas warnings

import pandas
pandas.options.mode.chained_assignment = None



---

# DataTypes


In [26]:
# string[start:stop:step]

word = "Hello There"
word = "Hello World!"
print("Printing in reverse " + word[::-1])
print("Printing in reverse and step = 2 " + word[::-2])
print("Printing in reverse and step = 3 " + word[::-3])

Printing in reverse !dlroW olleH
Printing in reverse and step = 2 !lo le
Printing in reverse and step = 3 !r l


## Enumerate


In [34]:
string = "Hello There"
char_list = list(enumerate(string))

print(f"Position of charecters are: {char_list}")

Position of charecters are: [(0, 'H'), (1, 'e'), (2, 'l'), (3, 'l'), (4, 'o'), (5, ' '), (6, 'T'), (7, 'h'), (8, 'e'), (9, 'r'), (10, 'e')]


## Finding Position of the charecter in strings


In [35]:
string = "Hello There"

# Printing the positions of the charecter 'e' in the above string using
# regular expressions.
import re
[i.start() for i in re.finditer('e', string)]

[1, 8, 10]

## Lists operations


In [46]:
my_list = ["Hello There", "Raghu"]
print(my_list)

my_list.insert(2, "Welcome")
print(my_list)

my_list.extend([1, 2, 3])
print(my_list)

index = my_list.index("Raghu")
print(index)

my_list.sort
print(my_list)

my_list.reverse()
print(my_list)

['Hello There', 'Raghu']
['Hello There', 'Raghu', 'Welcome']
['Hello There', 'Raghu', 'Welcome', 1, 2, 3]
1
['Hello There', 'Raghu', 'Welcome', 1, 2, 3]
[3, 2, 1, 'Welcome', 'Raghu', 'Hello There']


## Tuples
- These are like lists, but they are immutable


In [48]:
my_tupple = (1, 2)

print(my_tupple)

try:
  my_tupple.insert(1)
except Exception as e:
  print(f"Tupples are immutable, we cannot edit them. The tupple: {my_tupple}")

(1, 2)
Tupples are immutable, we cannot edit them. The tupple: (1, 2)


## Dictionary

In [49]:
my_information = {'name': "Raghunathan R",
                  'team': "BIS"
                  }

print(my_information)
print(my_information.keys())
print(my_information.values())

print(my_information['name'])

{'name': 'Raghunathan R', 'team': 'BIS'}
dict_keys(['name', 'team'])
dict_values(['Raghunathan R', 'BIS'])
Raghunathan R


## Random Number


In [54]:
import random
import numpy

# The seed method is used to make sure that the same random number is generated
# in all the runs

# For single random value
random.seed(9)
print(random.randint(0, 9))

# For four random value
print(numpy.random.randint(0, 9, size = 4))

# For only printing four unique values
print(random.sample(range(9), 4))

7
[2 2 7 2]
[5, 4, 1, 6]


In [60]:
import random
import string

random_string = string.ascii_letters + string.punctuation + string.digits

print(random_string)
for i in range(0, 5):
  print(random.choice(random_string))

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~0123456789
2
a
R
-
(


# Numpy Functions

- Numpy arrays are more fasters and space effecient than lists

In [1]:
import numpy as np
a = np.array([(1,2,3),(4,5,6)])
a1 = np.array([(1,2,3,4,5,6)])
a2 = np.array([1,2,3,4,5,6])

# Checking the .shape method for numpy
print(a)
print(a1)
print(a2)
print(a.shape)
print(a1.shape)
print(a2.shape)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
(2, 3)
(1, 6)
(6,)


In [3]:
# Specifing the dimensions of the array during creation
nine_dimensional_array = np.array([12], ndmin=9)

print(nine_dimensional_array)

[[[[[[[[[12]]]]]]]]]


## Numpy Arrange method
- The arange is used for printing in a more number line like form, the starting point, the ending point and the step

In [9]:
import numpy as np

print(np.arange(1, 10, 3))
print(np.arange(10, 1, -3))
print(np.arange(10, 1, -3)[::-1])
print(np.flip(np.arange(10, 1, -3)))

[1 4 7]
[10  7  4]
[ 4  7 10]
[ 4  7 10]


## Numpy Reshape method
- in this method, we path the dimensionality of the array that we need


In [10]:
array = np.arange(9).reshape(3, 3)

print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Linespace in Numpy and Axis

In [16]:
import numpy as np

array = np.linspace(1, 10, 10)
print(array)

# Axis in Numpy
array = np.array([(1, 2, 3),
                  (4, 5, 6)])
print(array)
print(array.mean(axis=0))
print(array.mean(axis=1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]
[2. 5.]


In [24]:
# np.concatenate((np.zeros((3, 3), dtype=int)), axis=1)

# Non zero method
a = np.array([1, 2, 0, 3, 0, 9, 9, 0, 0])
print(f"Positions of the non zero elements: {np.nonzero(a)}")
print(f"Non zero elements: {a[np.nonzero(a)]}")


Positions of the non zero elements: (array([0, 1, 3, 5, 6]),)
Non zero elements: [1 2 3 9 9]


In [30]:
x = np.array([
    (1, 2, 3),
    (4, 5, 6)
])

a = x.ravel()
print(a)
print(type(a))

a = a.tolist()
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
<class 'list'>


In [34]:
# Creating a 3 3x3 random integer array
random_array = np.random.randint(0, 10, size=(3, 3, 3))
print(random_array)

[[[3 8 7]
  [2 3 3]
  [7 3 9]]

 [[0 4 8]
  [1 8 0]
  [0 1 1]]

 [[8 0 8]
  [0 1 3]
  [1 6 6]]]


In [35]:
# Creating a 10x10 array with randome values and find its minimum and maximum
# values

array = np.random.random((10, 10))
array_min, array_max = array.min(), array.max()

print(array_min, array_max)

0.0047037033634355074 0.9570137718187883


In [42]:
# Exercise. Create the data frame needed

import random
import datetime
import pandas as pd

col1 = [chr(65 + i) for i in range(0,10)]
col2 = [chr(97 + i) for i in range(0,10)]
col3 = [random.randint(100,200) for i in range(10)]
col4 = random.sample(range(100,200), 10)
col5 = [i for i in range(0,20) if i%2 != 0]
col6 = datetime.datetime.now()

df=pd.DataFrame({"a":col1,"b":col2,"c":col3,"d":col4,"e":col5,"f":col6})
df


a  b    c    d   e                          f
0  A  a  110  126   1 2023-12-19 09:52:35.009406
1  B  b  197  141   3 2023-12-19 09:52:35.009406
2  C  c  105  173   5 2023-12-19 09:52:35.009406
3  D  d  151  120   7 2023-12-19 09:52:35.009406
4  E  e  185  118   9 2023-12-19 09:52:35.009406
5  F  f  176  145  11 2023-12-19 09:52:35.009406
6  G  g  185  100  13 2023-12-19 09:52:35.009406
7  H  h  156  184  15 2023-12-19 09:52:35.009406
8  I  i  146  148  17 2023-12-19 09:52:35.009406
9  J  j  171  119  19 2023-12-19 09:52:35.009406



---


# Flipkart Dataset

In [44]:
import pandas as pd

df = pd.read_csv("/content/Flipkart.csv", encoding="unicode_escape")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1952 entries, 0 to 1951
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Row ID                1952 non-null   int64  
 1   Order Priority        1952 non-null   object 
 2   Discount              1952 non-null   float64
 3   Unit Price            1952 non-null   float64
 4   Shipping Cost         1952 non-null   float64
 5   Customer ID           1952 non-null   int64  
 6   Customer Name         1952 non-null   object 
 7   Ship Mode             1952 non-null   object 
 8   Customer Segment      1952 non-null   object 
 9   Product Category      1952 non-null   object 
 10  Product Sub-Category  1952 non-null   object 
 11  Product Container     1952 non-null   object 
 12  Product Name          1952 non-null   object 
 13  Product Base Margin   1936 non-null   float64
 14  Country               1952 non-null   object 
 15  Region               

In [51]:
# Describe the numerical coloumns

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1952 entries, 0 to 1951
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Row ID                1952 non-null   int64  
 1   Order Priority        1952 non-null   object 
 2   Discount              1952 non-null   float64
 3   Unit Price            1952 non-null   float64
 4   Shipping Cost         1952 non-null   float64
 5   Customer ID           1952 non-null   int64  
 6   Customer Name         1952 non-null   object 
 7   Ship Mode             1952 non-null   object 
 8   Customer Segment      1952 non-null   object 
 9   Product Category      1952 non-null   object 
 10  Product Sub-Category  1952 non-null   object 
 11  Product Container     1952 non-null   object 
 12  Product Name          1952 non-null   object 
 13  Product Base Margin   1936 non-null   float64
 14  Country               1952 non-null   object 
 15  Region               

In [53]:
order_priority = df['Order Priority']

view1 = df[['Order Priority', 'Discount', 'Sales', 'Region']]
view1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1952 entries, 0 to 1951
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Order Priority  1952 non-null   object 
 1   Discount        1952 non-null   float64
 2   Sales           1952 non-null   float64
 3   Region          1952 non-null   object 
dtypes: float64(2), object(2)
memory usage: 61.1+ KB


In [56]:
# Finding the Frequencies for each catagory
order_priority.value_counts()

Low              398
Not Specified    396
High             391
Critical         390
Medium           376
Critical           1
Name: Order Priority, dtype: int64

In [64]:
# For showing the details of all the data
print(df.describe(include = "all"))

# For showing only numeric detaisl
df.Sales.describe()

              Row ID Order Priority     Discount   Unit Price  Shipping Cost  \
count    1952.000000           1952  1952.000000  1952.000000    1952.000000   
unique           NaN              6          NaN          NaN            NaN   
top              NaN            Low          NaN          NaN            NaN   
freq             NaN            398          NaN          NaN            NaN   
mean    19916.479508            NaN     0.048975   109.079221      12.968151   
std      5957.595627            NaN     0.031378   393.481301      17.414631   
min        64.000000            NaN     0.000000     1.140000       0.490000   
25%     19121.000000            NaN     0.020000     6.480000       3.230000   
50%     21164.500000            NaN     0.050000    20.990000       6.150000   
75%     23483.250000            NaN     0.080000   100.972500      14.362500   
max     26389.000000            NaN     0.210000  6783.020000     164.730000   

        Customer ID Customer Name    Sh

count     1952.000000
mean       985.828832
std       2559.900167
min          2.250000
25%         58.807500
50%        202.395000
75%        802.945000
max      45737.330000
Name: Sales, dtype: float64

In [66]:
# Printing the first 5 rows
df.head()

# Printing the first N rows for example, 12
df.head(12)

# Printing the last 5
df.tail(5)

Row ID Order Priority  Discount  Unit Price  Shipping Cost  Customer ID  \
1947   19842           High      0.01       10.90           7.46         3397   
1948   19843           High      0.10        7.99           5.03         3397   
1949   26208  Not Specified      0.08       11.97           5.81         3399   
1950   24911         Medium      0.10        9.38           4.93         3400   
1951   25914           High      0.10      105.98          13.99         3403   

      Customer Name    Ship Mode Customer Segment Product Category  ...  \
1947    Andrea Shaw  Regular Air   Small Business  Office Supplies  ...   
1948    Andrea Shaw  Regular Air   Small Business       Technology  ...   
1949    Marvin Reid  Regular Air   Small Business  Office Supplies  ...   
1950  Florence Gold  Express Air   Small Business        Furniture  ...   
1951  Tammy Buckley  Express Air         Consumer        Furniture  ...   

       Region State or Province         City  Postal Code Order Date  \
1947  Central          Illinois     Danville        61832   11-03-15   
1948  Central          Illinois     Danville        61832   11-03-15   
1949  Central          Illinois  Des Plaines        60016   29-03-15   
1950     East     West Virginia     Fairmont        26554   04-04-15   
1951     West           Wyoming     Cheyenne        82001   08-02-15   

     Ship Date    Profit Quantity ordered new   Sales Order ID  
1947  12-03-15 -116.7600                   18  207.31    87536  
1948  12-03-15 -160.9520                   22  143.12    87536  
1949  31-03-15  -41.8700                    5   59.98    87534  
1950  04-04-15  -24.7104                   15  135.78    87537  
1951  11-02-15  349.4850                    5  506.50    87530  

[5 rows x 25 columns]

# EDA Using Sweetviz
```
    pip install sweetviz
```

In [69]:
pip install sweetvix

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 28.5 MB/s eta 0:00:00


In [70]:
# Analysing and EDA using Sweeetvix

import sweetviz as sv

report = sv.analyze(df)
report.show_html()

                                             |          | [  0%]   00:00 -> (? left)

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.


In [72]:
# GroupBy using Data Frames

df[['Sales', 'Region']].groupby("Region").mean()

Sales
Region              
Central   792.022438
East     1249.306941
South     807.930136
West     1120.801213

In [74]:
# Aggregate Function in Data Frames
df.agg({"Sales":["min","max","median","sum"],
        "Discount":["min","max","median","sum"]})

Sales  Discount
min           2.250      0.00
max       45737.330      0.21
median      202.395      0.05
sum     1924337.880     95.60

# Question 2.

1. Print top five customer names by sales .
2. Print top customer name by discount.
3. Print all customer name start with "A" and ship mode is "Express Air" .
4. TO BE CONTINUED...

In [85]:
# 1. Print top five customer names by sales .

df[['Customer Name', 'Sales']].sort_values('Sales', ascending=False).head(5)

# OR
df1 = df[['Customer Name', 'Sales']]
df1.nlargest(5, 'Sales', keep='all')

Customer Name     Sales
967    Nina Horne Kelly  45737.33
295   Kristine Connolly  43046.20
258        Toni Swanson  31670.60
1459   Rosemary O'Brien  29718.53
1513        Yvonne Mann  27587.55

In [86]:
# 2. Print top customer name by discount.

df2 = df[['Customer Name', 'Discount']].sort_values('Discount', ascending=False).head(5)

# OR
df2.nlargest(5, 'Discount', keep='all')
df2.nlargest(1, 'Discount', keep='all')

Customer Name  Discount
1786  Kristine Singleton      0.21

In [87]:
# 3. Print all customer name start with "A" and ship mode is "Express Air" .

df[df['Customer Name'].str.startswith('A') & (df['Ship Mode'] == 'Express Air')]['Customer Name']

# OR



209               Angela Howe
275               Aaron Riggs
328      Alison Peters Wooten
357                  Ann Katz
477              Arthur Brady
651            Alex Nicholson
836            Alison Stewart
1009             Albert Tyson
1158               Annie Odom
1228               Anita Hahn
1267       Arnold Floyd Blair
1346    Arlene Wiggins Dalton
1477          Anthony Stanley
1483       Amy Hamrick Melvin
1496         Alicia Wood Shah
1561             Alison Jones
1634          Andrew Gonzalez
1748            Andrew Levine
1750            Andrew Levine
1844              Arthur Gold
1889           Alicia Maynard
1932         Annette McIntyre
1933         Annette McIntyre
Name: Customer Name, dtype: object