<a href="https://colab.research.google.com/github/raghunathan-unisys/ML_Automation_Training/blob/Training-Notes/Day_3_ML_TrainingNotes_20231220.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Models Continued


In [1]:
# Logestic Regression Model

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [4]:
data = {'Hlength': [150, 120, 175, 110, 95],
        'Weight': [75, 100, 50, 85, 72],
        'Gender': ['Female', 'Male', 'Female', 'Male', 'Male']
        }

df = pd.DataFrame(data, columns=['Hlength', 'Weight', 'Gender'])

# Getting the Dependent variables Y and the Independent variables X
X = df[['Hlength', 'Weight']]
Y = df['Gender']

# Fitting the data into the Logistic Regression model
reger = LogisticRegression()
reger.fit(X, Y)

hlength = int(input("Enter Hair Length: "))
weight = int(input("Enter your Weight: "))
x = [[hlength, weight]]
y = reger.predict(x)
print('Predicted Hlength is ',y)

Enter Hair Length: 150
Enter your Weight: 100
Predicted Hlength is  ['Female']


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


## Logistic Regression Example with Sample Dataset

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# load dataset
pima = pd.read_csv("/content/diabetes.csv")


#split dataset in features and target variable
feature_cols = ['Pregnancies', 'Insulin', 'BMI', 'Age','Glucose','BloodPressure']
X = pima[feature_cols] # Features
y = pima['Outcome'] # Target variable


# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=25)


# import the class
from sklearn.linear_model import LogisticRegression


# instantiate the model (using the default parameters)
logreg = LogisticRegression()


# fit the model with data
logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)


# import the metrics class
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)


print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[112  18]
 [ 25  37]]
Accuracy: 0.7760416666666666


# Question - Using Logistic Regression


In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("/content/Flipkart.csv", encoding="unicode_escape")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1952 entries, 0 to 1951
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Row ID                1952 non-null   int64  
 1   Order Priority        1952 non-null   object 
 2   Discount              1952 non-null   float64
 3   Unit Price            1952 non-null   float64
 4   Shipping Cost         1952 non-null   float64
 5   Customer ID           1952 non-null   int64  
 6   Customer Name         1952 non-null   object 
 7   Ship Mode             1952 non-null   object 
 8   Customer Segment      1952 non-null   object 
 9   Product Category      1952 non-null   object 
 10  Product Sub-Category  1952 non-null   object 
 11  Product Container     1952 non-null   object 
 12  Product Name          1952 non-null   object 
 13  Product Base Margin   1936 non-null   float64
 14  Country               1952 non-null   object 
 15  Region               

In [19]:
# Creating a Logistic Regression model

X = df[['Sales', 'Discount']]
y = df['Ship Mode']

# Spliting to Train and Test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Training the Model
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Printing the metrices
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print("Confusion matrix:\n", cnf_matrix)


print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Confusion matrix:
 [[  2   0  50]
 [  0   0  45]
 [  2   0 292]]
Accuracy: 0.7519181585677749


# Decision Tree

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.preprocessing import LabelEncoder


import pandas as pd
import numpy as np


df = pd.read_csv('/content/dtdb.csv')


lb = LabelEncoder()
df['outlook_'] = lb.fit_transform(df['outlook'])
df['temp_'] = lb.fit_transform(df['temp'] )
df['humidity_'] = lb.fit_transform(df['humidity'] )
df['windy_'] = lb.fit_transform(df['windy'] )
df['play_'] = lb.fit_transform(df['play'] )
X = df.iloc[:,5:9]
Y = df.iloc[:,9]


X_train, X_test , y_train,y_test = train_test_split(X, Y, test_size = 0.25, random_state = 100)


clf_entropy = DecisionTreeClassifier(criterion='entropy')
clf_entropy.fit(X_train.astype(int),y_train.astype(int))
y_pred_en = clf_entropy.predict(X_test)


print("Accuracy is :{0}".format(accuracy_score(y_test.astype(int),y_pred_en) * 100))

Accuracy is :50.0


## Example: Decision Tree with imporoved accuracy


In [22]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']


# load dataset
pima = pd.read_csv("D_ABC.csv", header=1, names=col_names)


#split dataset in features and target variable
feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
X = pima[feature_cols] # Features
y = pima.label # Target variable


# split X and y into training and testing sets
from sklearn.model_selection import train_test_split


# 25% testing, 75% training
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)


#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier


#Create a Gaussian Classifier
clf=RandomForestClassifier()


#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)
#############################################


#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy of RF:",metrics.accuracy_score(y_test, y_pred))


from sklearn import tree
clf1 = tree.DecisionTreeClassifier()


#Train the model using the training sets y_pred=clf.predict(X_test)
clf1.fit(X_train,y_train)


y_pred=clf1.predict(X_test)
#############################################


#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy of Decision Tree:",metrics.accuracy_score(y_test, y_pred))

Accuracy of RF: 0.8072916666666666
Accuracy of Decision Tree: 0.734375


# Neural Networks

# PCA Principle Component Analysis

# SVM Support Vector Machines